#!/usr/bin/expect
# By IBOTCORP.com | @Dakong

set password [lindex $argv 0];
set ::env(TERM) vt100
spawn screen -S lamp ./lamp.sh
expect "which apache you'd select" {send "\n"}
expect "Please input one or more number between 1 and 4" {send "\n"}
expect "which mysql you'd select" {send "1\n"}
expect "mysql data location" {send "\n"}
expect "mysql server root password" {send "$password\n"}
expect "which php you'd select" {send "5\n"}
expect "Please input one or more number between 1 and" {send "\n"}
expect "Please input one or more number between 1 and" {send "\n"}
expect "which kodexplorer you'd select" {send "\n\n"}
expect "Press any key" {send "\n"}
